# This file is automatically managed by <https://github.com/dtinth/repolicy>.
# Any manual changes to this file may be overwritten.

name: 'Sets up project'
description: 'Installs Node.js, pnpm, and project dependencies.'
runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: pnpm
    - name: Install dependencies and build
      run: pnpm install --prefer-offline
      shell: bash
